### ISSUE TITLE
Comments can only be added at the start of the file

### ISSUE THREAD

**Issue by daaniiieel** [daaniiieel/flex#3]
If not at the start of the file, a segfault occurs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4a7250]

goroutine 1 [running]:
flex/evaluator.evalInfixExpression(0x59724f, 0x1, 0x509aa0, 0x5d2360, 0x0, 0x0, 0xc0000a2b30, 0x444d3e)
	/home/daniel/flexlang/src/flex/evaluator/evaluator.go:193 +0x1f0
flex/evaluator.Eval(0x509720, 0xc0000c6050, 0xc0000962c0, 0x509720, 0xc0000c6050)
	/home/daniel/flexlang/src/flex/evaluator/evaluator.go:70 +0x10e8
flex/evaluator.Eval(0x5095a0, 0xc000098300, 0xc0000962c0, 0x5095a0, 0xc000098300)
	/home/daniel/flexlang/src/flex/evaluator/evaluator.go:26 +0xb23
flex/evaluator.evalProgram(0xc0000ac060, 0xc0000962c0, 0x4e8fbd, 0x40)
	/home/daniel/flexlang/src/flex/evaluator/evaluator.go:131 +0x9b
flex/evaluator.Eval(0x509820, 0xc0000ac060, 0xc0000962c0, 0x220, 0xc0000c2000)
	/home/daniel/flexlang/src/flex/evaluator/evaluator.go:20 +0xb5
main.main()
	/home/daniel/flexlang/src/flex/main.go:30 +0x2aa
exit status 2
```

**Comment by daaniiieel** [comment]
Fixed in 0.3.0
